name: creativefiefdoms
favicon: null
layout_spectrum: 0.87861
typography_spectrum: 0.87572
title: creative fiefdoms
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6d6c67'
    - '#41403b'
    - '#fafeff'
    - '#bc8b56'
    - '#d4d4d4'
  brandStrength: 0.875
  lightness: 0.1875
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
