name: creativefiefdoms
favicon: null
layout_spectrum: 0.23507
typography_spectrum: 0.43738
title: creative fiefdoms
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6d6c67'
    - '#41403b'
    - '#fafeff'
    - '#bc8b56'
    - '#d4d4d4'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
