name: creativefiefdoms
favicon: null
layout_spectrum: 0.32910223049111664
typography_spectrum: 0.8361505446955562
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8024108107201755
  lightness: 0.4642468460369855
  saturation: 0.16061855456791818
  rhythmicContrast: 0.02931490819901228
purpose: []
